services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 8009:6379
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: always
    networks:
      - redis_net

  idp:
    depends_on:
      - redis
    image: rediscommander/redis-commander:latest
    container_name: redis_comndr
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HTTP_USER=${HTTP_USER}
      - HTTP_PASSWORD=${HTTP_PASSWORD}
    ports:
      - 8010:8081
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
